ARG binFolder="bin/Release/netcoreapp3.1"
FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet build -c Release

# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:3.1
WORKDIR /app
COPY --from=build-env /app/$binFolder .
ENV ExePath=bin/Release/netcoreapp3.1
WORKDIR /app/$ExePath
ENTRYPOINT [ "dotnet", "PluginApp.dll"]