name: develop_build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/Achi054/index.json
      env:
      NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
    - name: Ensure GitHub NuGet Source
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/Achi054/index.json \
        -n github \
        -u ${{ secrets.REGISTRY_OWNER }} \
        -p ${{ secrets.NUGET_TOKEN }} \
        --store-password-in-clear-text
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
